name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: restore
      run: |
        dotnet tool restore
        dotnet paket restore
    - name: sonic-server
      run: bash ./Tests/test-env.sh
    - name: test
      run: dotnet fake build -t test
